filter:
  excluded_paths:
    - "tests/"
    - "example/"
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
build:
  environment:
    variables:
      COMPOSER_ROOT_VERSION: 2.0
    php:
      version: '8.0'
      ini:
        'xdebug.mode': 'coverage'
  nodes:
    coverage:
      tests:
        override:
          - php-scrutinizer-run
          - command: php vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover
